spring:
  application:
    name: project-zuul
  redis:
    host: 47.97.249.167
    port: 6379
    password: 123456

server:
  port: 8040

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    cart1:
      path: /**
      serviceId: project-web
      stripPrefix: true
    cart2:
      path: /user/**
      serviceId: project-web-user
      stripPrefix: false

  sensitive-headers:

#      stripPrefix: false
#    api-b:
#      path: /api/b/**
#      serviceId: hello-spring-cloud-web-admin-feign
#  ignored-patterns: /**/admin/**
#  prefix: /api
#  strip-prefix: true