spring:
  redis:
    host: 47.97.249.167
    port: 6379
    password: 123456

#≈‰÷√”¶”√√˚

  application:
    name: redis-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 60

server:
  port: 8028