
#≈‰÷√”¶”√√˚
spring:
  application:
    name: user-email

  mail:
    host: smtp.qq.com
    username: 1213668681@qq.com
    password: oyrivxaqqjyijgad
    default-encoding: utf-8

activeServerUrl: http://localhost:8030/user/active/


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 60

server:
  port: 8027

