spring:
  application:
    name: project-web
  redis:
    host: 47.97.249.167
    port: 6379
    password: 123456

  mvc:
    static-path-pattern: /**

  rabbitmq:
    host: 47.97.249.167
    port: 5672
    username: rabbit
    password: 123456

server:
  port: 8030
  servlet:
    context-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
